console.log("example 1:")
console.log("....0....")
console.log("...0.0...")
console.log("..0.0.0..")
console.log(".0.0.0.0.")
console.log("")
console.log("example 2:")
console.log(".0.0.0.0.")
console.log("..0.0.0..")
console.log("...0.0...")
console.log("....0....")
console.log("")
console.log("example 3:")
console.log("....0....")
console.log("...0.0...")
console.log("..0.0.0..")
console.log(".0.0.0.0.")
console.log("..0.0.0..")
console.log("...0.0...")
console.log("....0....")

